src/books/urls.py
from django.urls import path
from django.urls import include
from .models import Book, Comment

from . import views

urlpatterns = [

    # path('', views.BookListView.as_view(), name="book_list"),
    # path('^(?P<pk>\d+)/$', views.BookDetailView.as_view(), name="book_detail"),
    path('', views.book_list_view, name="book_list"),
    path('details/<int:index>/',views.book_detail_view, name='book_detail'),
    path('refined-search/', views.refined_view, name="refined_view"),
    path('sorted/', views.sorted_book, name="sorted"),
    path('book/<int:pk>/comment/<str:anon>/', views.add_review_to_book, name='add_review_to_book'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('books/', views.book_list_view),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    

]

src/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        )

app_name ='cart_home'
app_name ='cart_update'

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^update/$', cart_update, name='update'),
]

src/geektext/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.urls import path, include
from accounts import views as user_views
from accounts.views import guest_register_view
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('register/guest/', guest_register_view, name='guest_register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete'),
    path('books/', include('books.urls')),
    path('', include('bookstore.urls')),
    path('addresses/', include('addresses.urls')),
    path('cards/', include('cards.urls')),
    url('cart/', include("carts.urls", namespace='cart')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/books/models.py
from django.db import models
from django.db.models import Avg
from django.utils.timezone import now
import datetime

from django.db import models
from django.utils import timezone
import datetime

#from accounts.models import Profile


# Create your models here.
class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    full_name = models.CharField(max_length=30)
    email = models.EmailField(null=True)
    description = models.TextField(max_length=600, null=True, blank=True)
    dob = models.CharField(max_length=12, null=True, blank=True)
    birthplace = models.CharField(max_length=75, null=True, blank=True)
    education = models.CharField(max_length=100, null=True, blank=True)
    website = models.URLField(null=True)
    image = models.FileField(null=True, blank=True)

    def __str__(self):
        return u'%s' % self.full_name

    def get_absolute_url(self):
        return "/book/author/%s/" % self.id

    class Meta:
        ordering = ['full_name']

class Book(models.Model):
    authors = models.ManyToManyField(Author, blank=True)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=120)
    description = models.TextField(max_length=600, null=True, blank=True)
    image = models.FileField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=5, default=0)
    publication_date = models.CharField(max_length=12, null=True, blank=True)
    publication_date2 = models.DateField(default=datetime.date.today)
    genre = models.CharField(max_length=50, blank=True, null=True)
    pages = models.IntegerField(default=0)
    avg_rating = models.DecimalField(decimal_places=1, max_digits=2, default=0)
    sales_rank = models.IntegerField(default=0)
    top_sellers = models.BooleanField(default=False)
    #review = models.CharField(max_length=300)

    def __str__(self):
        return self.title

    # def __str__(self):
    #     return self.title

    def get_absolute_url(self):
        return "/book/%s/" % self.id

    # def author(self):
    #     return Author.objects.filter(book__authors__book=self.id).distinct()

    def rating_avg(self):
        book = Book.objects.get(id=self.id)
        # return list(book.rating_set.aggregate(Avg('rating')).values())[0]
        pass

    def rating_count(self):
        # return Rating.objects.all().filter(book=self).count()
        pass

    class Meta:
        ordering = ['title']

class Comment(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=200)
    #author = models.OneToOneField(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text
    

src/books/forms.py
from django import forms
from .models import Book, Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

src/books/views.py
import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.views import generic
from .models import Book,Author
from accounts.models import WishList, WishListNames
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.urls import reverse
from random import shuffle
from .forms import CommentForm
from .models import Book, Comment
from django.contrib.auth.decorators import login_required



class AllAuthorsView(generic.TemplateView):
    template_name = 'book_author.html'

    def get_context_data(self, **kwargs):
        context = super(AllAuthorsView, self).get_context_data(**kwargs)
        context['a'] = Author.objects.filter(full_name__startswith="A")
        context['b'] = Author.objects.filter(full_name__startswith="B")
        context['c'] = Author.objects.filter(full_name__startswith="C")
        context['d'] = Author.objects.filter(full_name__startswith="D")
        context['e'] = Author.objects.filter(full_name__startswith="E")
        context['f'] = Author.objects.filter(full_name__startswith="F")
        context['g'] = Author.objects.filter(full_name__startswith="G")
        context['h'] = Author.objects.filter(full_name__startswith="H")
        context['i'] = Author.objects.filter(full_name__startswith="I")
        context['j'] = Author.objects.filter(full_name__startswith="J")
        context['k'] = Author.objects.filter(full_name__startswith="K")
        context['l'] = Author.objects.filter(full_name__startswith="L")
        context['m'] = Author.objects.filter(full_name__startswith="M")
        context['n'] = Author.objects.filter(full_name__startswith="N")
        context['o'] = Author.objects.filter(full_name__startswith="O")
        context['p'] = Author.objects.filter(full_name__startswith="P")
        context['q'] = Author.objects.filter(full_name__startswith="Q")
        context['r'] = Author.objects.filter(full_name__startswith="R")
        context['s'] = Author.objects.filter(full_name__startswith="S")
        context['t'] = Author.objects.filter(full_name__startswith="T")
        context['u'] = Author.objects.filter(full_name__startswith="U")
        context['v'] = Author.objects.filter(full_name__startswith="V")
        context['w'] = Author.objects.filter(full_name__startswith="W")
        context['x'] = Author.objects.filter(full_name__startswith="X")
        context['y'] = Author.objects.filter(full_name__startswith="Y")
        context['z'] = Author.objects.filter(full_name__startswith="Z")
        return context


class BookListView(generic.ListView):
    template_name = 'book_list.html'
    model = Book

    def get_queryset(self):
        order = self.request.GET.get("sort")
        order2 = self.request.GET.get("order")
        queryset_list = Book.objects.all()

        query = self.request.GET.get("q")  # this gets the contents from the search bar 'q'
        if query:
            if query in 'Tech Valley Times Best Sellers':
                queryset_list = queryset_list.filter(tech_valley_best=1)
            elif query in 'Coming Soon':
                queryset_list = queryset_list.filter(publication_date__gt=datetime.date.today())
            elif 'Star' in query:
                if 'One' in query:
                    queryset_list = queryset_list.filter(avg_rating__range=(1, 1.9))
                elif 'Two' in query:
                    queryset_list = queryset_list.filter(avg_rating__range=(2, 2.9))
                elif 'Three' in query:
                    queryset_list = queryset_list.filter(avg_rating__range=(3, 3.9))
                elif 'Four' in query:
                    queryset_list = queryset_list.filter(avg_rating__range=(4, 4.5))
                elif 'Five' in query:
                    queryset_list = queryset_list.filter(avg_rating__range=(4.6, 5))

            else:
                queryset_list = queryset_list.filter(title__icontains=query).distinct() | \
                                queryset_list.filter(authors__full_name__icontains=query).distinct() | \
                                queryset_list.filter(genre__icontains=query).distinct()

        if order:
            order = order.strip()
            if query and order2 and queryset_list.filter(genre__icontains=query):
                queryset_list = queryset_list.order_by(order, order2)
            else:
                if order == 'sales_rank':
                    queryset_list = queryset_list.order_by(order).exclude(sales_rank=0)
                else:
                    queryset_list = queryset_list.order_by(order)
        else:
            if query and order2 and queryset_list.filter(genre__icontains=query):
                queryset_list = queryset_list.order_by("-tech_valley_best", order2)
            else:
                queryset_list = queryset_list.order_by("title")

        return queryset_list

    def get_context_data(self, **kwargs):
        context = super(BookListView, self).get_context_data(**kwargs)
        queryset_list = self.get_queryset()
        display_sort = self.request.GET.get("display")
        order = self.request.GET.get("sort")
        order2 = self.request.GET.get("order")
       
        
        context['total'] = self.get_queryset().count()
        query = self.request.GET.get("q")

        if query:
            context['q'] = query

        if order:
            context['sort'] = order
            if order == 'title':
                context['sorting'] = "Title - A to Z"
            elif order == '-title':
                context['sorting'] = "Title - Z to A"
            elif order == '-avg_rating':
                context['sorting'] = "Top Rated"
            elif order == 'publication_date':
                context['sorting'] = "Oldest"
            elif order == '-publication_date':
                context['sorting'] = "Newest"
            elif order == 'authors':
                context['sorting'] = "Author(s) A - Z"
            elif order == '-authors':
                context['sorting'] = "Author(s) Z - A"
            elif order == 'price':
                context['sorting'] = "Price - Low to High"
            elif order == '-price':
                context['sorting'] = "Price - High to Low"
            elif order == 'sales_rank':
                context['sorting'] = "Top Sellers"
            elif order == '-tech_valley_best':
                context['sorting'] = "Tech Valley Best Sellers"
        else:
            if query and Book.objects.filter(genre__icontains=query):
                context['sort'] = "-tech_valley_best"
                context['order'] = "-rating"
                context['sorting'] = "Tech Valley Best Sellers"
            else:
                context['sort'] = "title"
                context['sorting'] = "Title - A to Z"

        if display_sort:
            if queryset_list.count() > int(display_sort):
                context['display_sort_num'] = display_sort
            else:
                context['display_sort_num'] = display_sort
        else:
            if queryset_list.count() > 10:
                context['display_sort_num'] = 10
            else:
                context['display_sort_num'] = 10

        if order2:
            context['order'] = order2

        return context

    def get_paginate_by(self, queryset):
        display_sort = self.request.GET.get("display")
        if display_sort:
            if queryset.count() > int(display_sort):
                paginate_by = display_sort
            else:
                paginate_by = queryset.count()
        else:
            if queryset.count() > 10:
                paginate_by = 10
            else:
                paginate_by = queryset.count()

        return paginate_by


class BookDetailView(generic.DetailView):
    template_name = 'book_detail.html'
    model = Book

    def get_context_data(self, **kwargs):
        context = super(BookDetailView, self).get_context_data(**kwargs)
        number = cart_count(self.request)
        context['number'] = number
        author = Author.objects.filter(book=self.kwargs.get("pk")).distinct()
        context['author_books'] = Book.objects.filter(authors__book__authors__in=author).distinct().exclude(
        pk=self.kwargs.get("pk"))
        return context


def book_list_view(request):
    books = Book.objects.all()
    authors = Author.objects.all()
    temp_list = []
    if request.method == 'POST':
        search_book = request.POST.get('book-field')
        search_result = []
        for item in books:
            if search_book.lower() in item.title.lower():
                search_result.append(item)
            else:
                for auth in item.authors.all():
                    if search_book.lower() in auth.full_name.lower():
                        search_result.append(item)
        if not search_result:
            messages.info(request, 'No match found..!')

        for item in search_result:
            temp_list.append(item.id)
        request.session['book_list'] = temp_list

        page = request.GET.get('page', 1)

        paginator = Paginator(search_result, 12)
        try:
            book_by_page = paginator.page(page)
        except PageNotAnInteger:
            book_by_page = paginator.page(1)
        except EmptyPage:
            book_by_page = paginator.page(paginator.num_pages)

        context = {'book_by_page': book_by_page}
        return render(request, 'book_list.html', context)

    for item in books:
        temp_list.append(item.id)
    request.session['book_list'] = temp_list

    page = request.GET.get('page', 1)

    paginator = Paginator(books, 12)
    try:
        book_by_page = paginator.page(page)
    except PageNotAnInteger:
        book_by_page = paginator.page(1)
    except EmptyPage:
        book_by_page = paginator.page(paginator.num_pages)

src/books/templates/book_add_review.html
{% extends "bookstore/base.html" %}
{% load crispy_forms_tags %}

{% block register_content %}
    <h1>New Review</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        <!-- {{ form.as_p }} -->
        <fieldset class="form-group">
                {{ form|crispy }}
        </fieldset>
        <button type="submit" class="save btn btn-default">Send Review</button>
    </form>
{% endblock register_content %}

src/books/templates/book_author.html
{% extends "bookstore/base.html" %}
{% block title %}Authors | {{ block.super }}{% endblock %}
{% load static from staticfiles %}


{% block content %}
    <div class="container">
        <div class="row" style="margin-bottom: 35px;">
            <div class="col-md-8 col-md-offset-2 col-sm-offset-1">
                <ul class="list-inline">
                    <li><a href="#A">A</a></li>
                    <li><a href="#B">B</a></li>
                    <li><a href="#C">C</a></li>
                    <li><a href="#D">D</a></li>
                    <li><a href="#E">E</a></li>
                    <li><a href="#F">F</a></li>
                    <li><a href="#G">G</a></li>
                    <li><a href="#H">H</a></li>
                    <li><a href="#I">I</a></li>
                    <li><a href="#J">J</a></li>
                    <li><a href="#K">K</a></li>
                    <li><a href="#L">L</a></li>
                    <li><a href="#M">M</a></li>
                    <li><a href="#N">N</a></li>
                    <li><a href="#O">O</a></li>
                    <li><a href="#P">P</a></li>
                    <li><a href="#Q">Q</a></li>
                    <li><a href="#R">R</a></li>
                    <li><a href="#S">S</a></li>
                    <li><a href="#T">T</a></li>
                    <li><a href="#U">U</a></li>
                    <li><a href="#V">V</a></li>
                    <li><a href="#W">W</a></li>
                    <li><a href="#X">X</a></li>
                    <li><a href="#Y">Y</a></li>
                    <li><a href="#Z">Z</a></li>
                </ul>
            </div>
        </div>
        <div class="row authors-content">
            <div class="col-xs-6 col-sm-4 col-sm-offset-2">
                <div id="A">
                    <h3>A</h3>
                    <ul>
                        {% for auth in a %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="B">
                    <h3>B</h3>
                    <ul>
                        {% for auth in b %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="C">
                    <h3>C</h3>
                    <ul>
                        {% for auth in c %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="D">
                    <h3>D</h3>
                    <ul>
                        {% for auth in d %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="E">
                    <h3>E</h3>
                    <ul>
                        {% for auth in e %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="F">
                    <h3>F</h3>
                    <ul>
                        {% for auth in f %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="G">
                    <h3>G</h3>
                    <ul>
                        {% for auth in g %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="H">
                    <h3>H</h3>
                    <ul>
                        {% for auth in h %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="I">
                    <h3>I</h3>
                    <ul>
                        {% for auth in i %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="J">
                    <h3>J</h3>
                    <ul>
                        {% for auth in j %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="K">
                    <h3>K</h3>
                    <ul>
                        {% for auth in k %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="L">
                    <h3>L</h3>
                    <ul>
                        {% for auth in l %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-xs-6 col-sm-4 col-sm-offset-2">
                <div id="M">
                    <h3>M</h3>
                    <ul>
                        {% for auth in m %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="N">
                    <h3>N</h3>
                    <ul>
                        {% for auth in n %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="O">
                    <h3>O</h3>
                    <ul>
                        {% for auth in o %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="P">
                    <h3>P</h3>
                    <ul>
                        {% for auth in p %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="Q">
                    <h3>Q</h3>
                    <ul>
                        {% for auth in q %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="R">
                    <h3>R</h3>
                    <ul>
                        {% for auth in r %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="S">
                    <h3>S</h3>
                    <ul>
                        {% for auth in s %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="T">
                    <h3>T</h3>
                    <ul>
                        {% for auth in t %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="U">
                    <h3>U</h3>
                    <ul>
                        {% for auth in u %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="V">
                    <h3>V</h3>
                    <ul>
                        {% for auth in v %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="W">
                    <h3>W</h3>
                    <ul>
                        {% for auth in w %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="X">
                    <h3>X</h3>
                    <ul>
                        {% for auth in x %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="Y">
                    <h3>Y</h3>
                    <ul>
                        {% for auth in y %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
                <div id="Z">
                    <h3>Z</h3>
                    <ul>
                        {% for auth in z %}
                            <li><a href="/books/?q={{ auth.full_name }}">{{ auth.full_name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/books/templates/book_rating.html
{% load static %}
{% load ratings %}
<html>

<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

<body>
    {% ratings book %}
</body>

</html>

src/books/templates/book_review.html
{% extends "bookstore/base.html" %}
{% block title %}Checkout | {{ block.super }}{% endblock %}
{% load static from staticfiles %}

{% comment %} {% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Write Review</button>
    </form>
    
    </div>


{% endblock %}

src/books/templates/update-cart.html
<form method='POST'action ='{% url "cart:update" %}' > {% csrf_token %}
    <input type='hidden' name='product_id' value='{{ product.id }}' />
    <!--- <a href='{% url "cart:update" %}'>-->                        
     <!---<button class="btn btn-success">Add To Cart </button> --> 
    {% if in_cart %}    
        <button  type = 'submit' class='btn btn-link btn-sm'>Remove</button>
    {% else %}
        {% if product in cart.products.all %}
        <button  type = 'submit' class='btn btn-link'>Remove</button>
        {% else %}
        <button   type = 'submit' class='btn btn-success'>Add To Cart</button>
        {% endif %}
    {% endif %}
</form>